<!DOCTYPE html>
<html>
<head>
    <title>Админ-панель</title>
    <link rel="stylesheet" href="../static/admin-panel.css">
</head>
<body>
<header>
    <h1>Админ-панель</h1>
</header>
<nav>
    <ul>
        <li><a href="/">Главная</a></li>
        <li><a href="/admin/account-register">Добавить эккаунт</a></li>
        <li><a href="#">Статистика</a></li>
        <li><a href="#">Выход</a></li>
    </ul>
</nav>
<main>
    <h2>Добро пожаловать в админ-панель!</h2>
    <p>Здесь вы можете управлять своими данными и настройками.</p>
</main>
<footer>
    <p>© 2023 Админ-панель. Все права защищены.</p>
</footer>
</body>
</html>
